// <auto-generated />
using System;
using Congo.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Congo.WebApi.Data.Migrations
{
    [DbContext(typeof(CongoContext))]
    [Migration("20211020114637_AddedMoreSampleProducts")]
    partial class AddedMoreSampleProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Congo.WebApi.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8730bfc5-2346-48d5-8daf-f19d2a829c98"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Screwdriver",
                            Price = 331.583643352666m
                        },
                        new
                        {
                            Id = new Guid("03517da3-d3d1-4267-9a7d-0fe039a23425"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "AMD Ryzen 7 5900X",
                            Price = 798.685430532422m
                        },
                        new
                        {
                            Id = new Guid("94377578-c249-40ff-87d7-bbb965893df1"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "A Rock",
                            Price = 217.587337448782m
                        },
                        new
                        {
                            Id = new Guid("84fc9da7-a72c-491b-a5eb-27b7b5366bfc"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "5-Piece Gardening Kit",
                            Price = 414.537652129805m
                        },
                        new
                        {
                            Id = new Guid("fee898f3-8630-4632-924f-52c41cdd2246"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Box of Chocolates",
                            Price = 189.636132677629m
                        },
                        new
                        {
                            Id = new Guid("62b47a87-2f12-4221-9195-815acec605c8"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Window Cleaning Solution",
                            Price = 657.576191211169m
                        },
                        new
                        {
                            Id = new Guid("5418c5e4-51c1-4be7-867b-23ab69259095"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Paper shredder",
                            Price = 96.2439118548175m
                        },
                        new
                        {
                            Id = new Guid("00b306e8-164e-4881-b9ef-e180bf5f7d4a"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Xbox Controller",
                            Price = 499.487247335267m
                        },
                        new
                        {
                            Id = new Guid("4a4ab74b-1205-415e-93c4-dc87d0e37575"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "LED Light Bulb - 8 pack",
                            Price = 199.710894823652m
                        },
                        new
                        {
                            Id = new Guid("4dc42389-013a-4b97-8858-587683d93587"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "A Dance With Dragons - Hard Cover",
                            Price = 976.883902110818m
                        },
                        new
                        {
                            Id = new Guid("5c08caa4-4cff-451c-ae34-96ba993e5035"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Licensed Steel Pants",
                            Price = 259.713725624254m
                        },
                        new
                        {
                            Id = new Guid("83a6dc04-30a7-4be2-a98a-e6102da16ef1"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Practical Steel Gloves",
                            Price = 493.797046540457m
                        },
                        new
                        {
                            Id = new Guid("9aff7b6d-245a-48b6-bb11-e70d5558cce7"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Refined Plastic Shoes",
                            Price = 623.719017679453m
                        },
                        new
                        {
                            Id = new Guid("bc927a9f-e066-4a5a-8751-9f8c1e4c821e"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Incredible Fresh Fish",
                            Price = 521.400573404474m
                        },
                        new
                        {
                            Id = new Guid("06301511-f05c-49d4-a99f-dd7ac24dad1e"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Practical Granite Cheese",
                            Price = 541.776629823868m
                        },
                        new
                        {
                            Id = new Guid("b528af0c-bbc1-4263-801c-b143b6aeb63a"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Sleek Soft Chair",
                            Price = 379.418682911875m
                        },
                        new
                        {
                            Id = new Guid("41ce9544-79ce-4177-a13a-994010c623e7"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Generic Steel Chair",
                            Price = 202.787549832984m
                        },
                        new
                        {
                            Id = new Guid("36d4ded2-b436-4495-9ba7-32eed3d6c1e3"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Refined Concrete Shoes",
                            Price = 143.025703857446m
                        },
                        new
                        {
                            Id = new Guid("85597b9a-f24f-424a-bc8a-e8a16f3123ca"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Tasty Rubber Table",
                            Price = 366.157638220437m
                        },
                        new
                        {
                            Id = new Guid("f772c0c9-e480-4539-a70f-d4f0e50afb4d"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Handmade Steel Ball",
                            Price = 857.057672045002m
                        },
                        new
                        {
                            Id = new Guid("cbd243c1-5416-44b7-a3f1-1f85ec521aca"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Jewelery",
                            Price = 538.416145007101m
                        },
                        new
                        {
                            Id = new Guid("6aff83f7-347f-4e53-8e3e-fef2fe387ee5"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Refined Cotton Gloves",
                            Price = 333.070613260195m
                        },
                        new
                        {
                            Id = new Guid("266e413c-2b6e-4a74-880f-69caa0417886"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Generic Rubber Pants",
                            Price = 367.287782614034m
                        },
                        new
                        {
                            Id = new Guid("c303b5a2-91d2-476b-9a6a-6d44ad4495db"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Fantastic Plastic Table",
                            Price = 474.35146603914m
                        },
                        new
                        {
                            Id = new Guid("3f242320-6551-43ba-9d0f-90b991de40ed"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Screwdriver",
                            Price = 570.942643662204m
                        },
                        new
                        {
                            Id = new Guid("76130ab1-800c-4b8d-8c57-aa369822d49c"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "AMD Ryzen 7 5900X",
                            Price = 105.361059035124m
                        },
                        new
                        {
                            Id = new Guid("26811ed8-02fb-475b-a895-65105f56463a"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "A Rock",
                            Price = 29.9549600102403m
                        },
                        new
                        {
                            Id = new Guid("982c1fa5-806d-453a-955e-40a1b0a5293c"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "5-Piece Gardening Kit",
                            Price = 814.20028616196m
                        },
                        new
                        {
                            Id = new Guid("d32eaa9d-c382-4313-a938-645e031f52f4"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Box of Chocolates",
                            Price = 334.044173271197m
                        },
                        new
                        {
                            Id = new Guid("cc503db9-189c-4fb3-b525-61beff664e3d"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Window Cleaning Solution",
                            Price = 283.883111852414m
                        },
                        new
                        {
                            Id = new Guid("7ff9d613-f177-4585-b69c-68fa96551339"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Paper shredder",
                            Price = 236.233716050984m
                        },
                        new
                        {
                            Id = new Guid("d7cb17ea-6684-4439-9be0-a2ca55aad2a0"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Xbox Controller",
                            Price = 797.477404482666m
                        },
                        new
                        {
                            Id = new Guid("3767a915-c0af-4b64-b3e6-8c834c349356"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "LED Light Bulb - 8 pack",
                            Price = 177.567304362588m
                        },
                        new
                        {
                            Id = new Guid("1b839928-4a82-4528-9399-d92c5787f999"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "A Dance With Dragons - Hard Cover",
                            Price = 27.9466723457336m
                        },
                        new
                        {
                            Id = new Guid("35813104-0708-4c0d-ab32-42541c7cb1d1"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Licensed Steel Pants",
                            Price = 601.436806830096m
                        },
                        new
                        {
                            Id = new Guid("683b2bcd-c42c-4a1f-b245-d7c9a3817c2e"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Practical Steel Gloves",
                            Price = 107.722829317792m
                        },
                        new
                        {
                            Id = new Guid("2e0e3e45-28f0-4056-b027-8e71fb218f6d"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Refined Plastic Shoes",
                            Price = 773.426819913535m
                        },
                        new
                        {
                            Id = new Guid("c157d2c1-3b80-4eb6-99a2-364a312a96e5"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Incredible Fresh Fish",
                            Price = 741.761513731112m
                        },
                        new
                        {
                            Id = new Guid("1b9bb5c9-7825-4849-a093-a28448489096"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Practical Granite Cheese",
                            Price = 722.345746221894m
                        },
                        new
                        {
                            Id = new Guid("3adf7f41-0675-4e29-ba0d-c664381269d1"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Sleek Soft Chair",
                            Price = 769.439450031132m
                        },
                        new
                        {
                            Id = new Guid("d99b733f-d23b-4f5f-bbb8-6ba9d48d52e4"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Generic Steel Chair",
                            Price = 48.0442431250467m
                        },
                        new
                        {
                            Id = new Guid("281c10e1-724a-4c11-8f85-40416f3f3a5e"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Refined Concrete Shoes",
                            Price = 93.5110182706458m
                        },
                        new
                        {
                            Id = new Guid("e17bfe95-006b-46bc-b4ee-c3e451a0397d"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Tasty Rubber Table",
                            Price = 223.84518762416m
                        },
                        new
                        {
                            Id = new Guid("96c8e13f-46c3-4ddb-930c-9b5ff819b001"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Handmade Steel Ball",
                            Price = 87.2483528553407m
                        },
                        new
                        {
                            Id = new Guid("4fb0810d-41ec-4819-a546-c164f467f5c5"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Jewelery",
                            Price = 120.564707629427m
                        },
                        new
                        {
                            Id = new Guid("a8d29e39-a550-4bc2-94eb-a7ceae88b848"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Refined Cotton Gloves",
                            Price = 866.484198041733m
                        },
                        new
                        {
                            Id = new Guid("e5b7a2fd-1838-44de-91d6-e02b857f857f"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Generic Rubber Pants",
                            Price = 706.623188653566m
                        },
                        new
                        {
                            Id = new Guid("d299db9b-0417-4432-87f7-6f27eb85f95d"),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vestibulum lacus augue, a tempor enim sollicitudin eu. Pellentesque odio nulla, maximus id mattis posuere, semper ac massa. Donec quis lectus eros. Sed ac fringilla nunc. Proin lacus nisi, fermentum quis interdum nec, blandit in sapien. Phasellus bibendum volutpat tortor, a sagittis sapien finibus id. Etiam urna est, sagittis eget orci et, finibus luctus lacus. ",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Fantastic Plastic Table",
                            Price = 295.138525146371m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
